name: learn-github-actions
on: [push]
jobs:
  chech-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses :action/setup-node@v3
        with:
            node-version: '14'
        - run: npm install -g bats
        - run bats -v
